# Generated by Django 5.1 on 2025-02-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_birthdaydiscountsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthdaydiscountsettings',
            options={'verbose_name': 'Настройка скидки на день рождение'},
        ),
        migrations.AlterField(
            model_name='birthdaydiscountsettings',
            name='discount_percentage',
            field=models.PositiveIntegerField(verbose_name='Процент скидки'),
        ),
    ]
