# Generated by Django 5.1 on 2025-05-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_birthdaydiscountsettings_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
