# Generated by Django 5.1 on 2025-05-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_category_product_category'),
        ('promotions', '0004_delete_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название праздника')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('day', models.PositiveSmallIntegerField(verbose_name='День')),
                ('products', models.ManyToManyField(blank=True, to='products.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Праздник',
                'verbose_name_plural': 'Праздники',
            },
        ),
    ]
