# Generated by Django 5.1 on 2025-01-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
