# Generated by Django 5.1 on 2025-01-23 22:08

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='products/photos/%Y/%m'),
        ),
    ]
