# Generated by Django 5.1 on 2025-02-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_options_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_case',
            field=models.BooleanField(default=False, verbose_name='Чехол'),
        ),
    ]
