# Generated by Django 5.1 on 2025-02-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quantity_of_cases',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество купленных чехлов'),
        ),
    ]
