# Generated by Django 5.1 on 2025-02-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_quantity_of_cases'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='ad_slides/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Рекламный слайд',
                'verbose_name_plural': 'Рекламные слайды',
            },
        ),
    ]
