# Generated by Django 5.1 on 2025-03-17 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_free_cases'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель телефона')),
            ],
            options={
                'verbose_name': 'Модель телефона',
                'verbose_name_plural': 'Модели телефонов',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='phone_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.phonemodel', verbose_name='Модель телефона'),
        ),
    ]
