# Generated by Django 5.1 on 2025-05-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_phonemodel_user_phone_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cluster',
            field=models.CharField(blank=True, choices=[('K2', 'Подарочники'), ('K3', 'Частые'), ('K4', 'Спящие')], max_length=10, null=True, verbose_name='Кластер'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_cluster_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
