# Generated by Django 5.1 on 2025-05-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_cluster_user_last_cluster_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_discount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Welcome скидка'),
        ),
    ]
