# Generated by Django 5.1 on 2025-05-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_welcome_discount'),
        ('products', '0008_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entered_k4_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='избранные товары'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_cluster_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления кластера'),
        ),
    ]
