# Generated by Django 5.1 on 2025-05-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_entered_k4_at_alter_user_favorite_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entered_k4_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата входа в кластер K4(спящие)'),
        ),
    ]
